### PR TITLE
drop `noarch: python` to allow fine-grained pinning of urllib3 depending on python version

### PR DESCRIPTION
**Pull request by 0xbe7a**
- drop noarch
- MNT: Re-rendered with conda-build 3.28.2, conda-smithy 3.30.4, and conda-forge-pinning 2024.02.13.22.01.17
- bump build

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tkelman** [comment]
This came up recently in #1465, I made a branch where we can push specific releases non-noarch. What is this blocking?

**Comment by tkelman** [comment]
If noarch is off, then supporting the less-common architectures or new python versions requires a migration, so there won't be builds of all the earlier versions that could be installed. Not supporting version-specific dependencies is a bit of an annoying limitation of noarch, which is why I'm curious what this is blocking. The boto/aws stack is historically slow at relaxing their dependency versions.

Would a PR to add arm64 support to the `arch-specific` branch (along with any version bumps you'd like) be sufficient for now? Looks like python 3.8 should get dropped later this year around when 3.13 comes out, but 3.9 has a while left.

**Comment by 0xbe7a** [comment]
The pin cruicially contains urllib3 version 2, which my application absolutely depends on. Adding arm64 builds to the single non-narch builds would solve my problem for now, but I prefer to move the package to non-narch until the conditional dependencies can be removed. Having only a single build will cause the branch to stop receiving automatic updates and migrations by default and the build becoming outdated unless manually updated.

Since this feedstock only has relatively simple dependencies, it will receive automatic migrations through the autotick bot for e.g. Python 3.13 and new architectures pretty much as soon as Python 3.13 or new architectures are available on the conda-forge, so I don't quite agree with your reasoning.

Also what are the less-common architectures we would miss without noarch: python? We could add windows-arm64 (?) and PowerPC builds if required

**Comment by tkelman** [comment]
Whatever's not enabled by default, linux arm and ppc is mostly what I was thinking of.

New python versions or architectures would only have builds available for versions released after the migration gets merged here when it isn't noarch. It's all the releases of the package from before those possible migrations that I'm concerned about.

**Comment by 0xbe7a** [comment]
You can also release new builds for old versions after the migration. @ocefpaf can you give some guidance here?

**Comment by tkelman** [comment]
This releases about 5 times a week upstream, in my eyes needing urllib3 2.0 is more of a special case worthy of being maintained manually on a branch for now than, say, allowing any of the botocore versions that come out between disabling noarch and the future python 3.13 migration to be installed on python 3.13 (likewise with future pypy versions, etc).

**Comment by pavelzw** [comment]
how about two `noarch` variants using `conda_build_config.yaml`, one with `python >=3.8` + `urllib3 >=1.25.4,<1.27` and one with `python >=3.10` + `urllib3 >=1.25.4,<2.1`?

**Comment by tkelman** [comment]
If that's possible, that'd be ideal.

**Comment by pavelzw** [comment]
in conda-build it's definitely possible but maybe conda-smithy complains about such a setup...

**Comment by pavelzw** [comment]
I tried it out now with

```yml
requirements:
  host:
    - python >=3.8  # [python_version == "old"]
    - python >=3.10  # [python_version == "new"]
    - pip
  run:
    - python >=3.8  # [python_version == "old"]
    - python >=3.10  # [python_version == "new"]
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27  # [python_version == "old"]
    # https://github.com/boto/botocore/pull/3034
    - urllib3 >=1.25.4,<2.1  # [python_version == "new"]
```

and `conda_build_config.yaml` like this:
```yml
python_version:
- 'new'
- 'old'
```

Unfortunately, conda-smithy still complains :(

```
❯ conda-smithy recipe-lint recipe
recipe has some lint:
  `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
```

So it unfortunately doesn't seem to be possible :/

**Comment by pavelzw** [comment]
this can be closed, right?

**Pull request closed without merging**
