### PR TITLE
Make urllib depend on python version

### PR DESCRIPTION
**Pull request by pavelzw**
See https://github.com/conda-forge/botocore-feedstock/pull/1479#issuecomment-1951450015

### CODE REVIEW

**Comment by pavelzw** [comment]
I mean conda-build works... only the linter complains

**Comment by pavelzw** [comment]
@tkelman @0xbe7a i think it's okay to ignore the failing linter in this case.

**Comment by pavelzw** [comment]
Closes #1479

**Comment by tkelman** [comment]
Cool thanks for trying this out! So that linter message only applies to the usual built-in selectors right? Is the reason we get away with it here because the selector is our own custom variant thing?

**Comment by pavelzw** [comment]
Exactly. My guess would be that they wanted to prevent stuff like `# [py38]` because this won't work out of the box as the python version is not one specific version.

**Comment by 0xbe7a** [comment]
I've opened https://github.com/conda-forge/conda-smithy/pull/1843 to allow selectors based on the local cbc in `noarch` packages

**Comment by tkelman** [comment]
Let's give this a try on main for a while and see if there are any issues other than the linter. If there are, we can relegate it to a branch, it could supersede the `arch-specific` branch where we turned off noarch.

**Pull request merged**
